version: '3.8'
services:
  app:
    build: .
    container_name: email-service
    user: root
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '3000:3000'
      - '9229:9229'
    environment:
      NODE_ENV: development
    tty: true
